#ifndef TIMER_CONFIG_H
#define TIMER_CONFIG_H

#define TIMER0_DEFAULT_MODE             TIMER0_CTC_MODE
#define TIMER0_DEFAULT_OC0_MODE         TIMER0_OC0_DISCONNECTED
#define TIMER0_DEFAULT_PRESCALER        TIMER_PRESCALER_64
#define TIMER0_DEFAULT_START_VALUE      0
#define TIMER0_DEFAULT_COMPARE_VALUE    250

#define TIMER1_DEFAULT_MODE             TIMER1_CTC_OCR1A_MODE
#define TIMER1_DEFAULT_OC1A_MODE        TIMER1_OC1A_DISCONNECTED
#define TIMER1_DEFAULT_START_VALUE      0
#define TIMER1_DEFAULT_COMPARE_VALUE    250

#define TIMER2_DEFAULT_MODE             TIMER2_CTC_MODE
#define TIMER2_DEFAULT_OC2_MODE         TIMER2_OC2_DISCONNECTED
#define TIMER2_DEFAULT_PRESCALER        TIMER_PRESCALER_64
#define TIMER2_DEFAULT_START_VALUE      0
#define TIMER2_DEFAULT_COMPARE_VALUE    250

#endif 